# .golangci.yml - golangci-lint configuration
run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - revive
    - misspell
    - unconvert
    - prealloc
    - nakedret
    - gosec
    
  disable:
    - exhaustive
    - funlen
    - gocognit
    - gocyclo
    - lll
    - dupl
    - wrapcheck
    - testpackage
    - paralleltest

issues:
  max-issues-per-linter: 0
  max-same-issues: 0 