{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-janitor-go.fullname" . }}
  labels:
    {{- include "kube-janitor-go.labels" . | nindent 4 }}
  annotations:
    {{- include "kube-janitor-go.annotations" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kube-janitor-go.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kube-janitor-go.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }} 