{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-janitor-go.fullname" . }}
  labels:
    {{- include "kube-janitor-go.labels" . | nindent 4 }}
  annotations:
    {{- include "kube-janitor-go.annotations" . | nindent 4 }}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["list", "get", "delete"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list"]
  {{- with .Values.rbac.additionalRules }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }} 